---
  yarnPath: ".yarn/releases/yarn-berry.cjs"
  nodeLinker: node-modules
  npmRegistries: 
    //npm.fontawesome.com:
      npmAlwaysAuth: true
      npmAuthToken: "9383956D-36A5-4FCE-8B09-7C31FA740F21"
    //pkgs.dev.azure.com/sauter-software/_packaging/sauter-cloud-npm-packages/npm/registry/:
      npmAlwaysAuth: false
      npmAuthIdent: "c2F1dGVyLXNvZnR3YXJlOnBramJxdTc2d2YzbWNoMmRqYmtmcTJhbDNiY3dxaWNldmczbGZveGVlcGhkcWRjM296aHE="

  npmScopes:
    fortawesome:
      npmRegistryServer: https://npm.fontawesome.com/
    sauter:
      npmRegistryServer: https://pkgs.dev.azure.com/sauter-software/_packaging/sauter-cloud-npm-packages/npm/registry/

